volumes:
  postgres:

services:
  web:
    image: nginx:latest
    ports:
    - "8000:80"
    volumes:
    - ./projectroot:/projectroot
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./proxy.conf:/etc/nginx/proxy.conf
    - ./fastcgi.conf:/etc/nginx/fastcgi.conf
    - ./mime.types:/etc/nginx/mime.types
  fpm:
    build: ./fpm
    volumes:
    - ./projectroot:/projectroot
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: craft
    volumes:
      - postgres:/var/lib/postgresql/data
    